[package]
name = "yew-app"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.27"
wasm-bindgen = "0.2.100"
wasm-logger = "0.2.0"
web-sys = "0.3.77"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
