name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Trunk
      uses: jetli/trunk-action@v0.5.0
    - name: Install wasm
      working-directory: yew-app
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      working-directory: yew-app
      run: trunk build --release true
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: yew-app/dist/
